"""users table

Revision ID: 0e2f58f0d553
Revises: 
Create Date: 2020-07-27 01:56:20.510640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2f58f0d553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('user_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
