"""nc

Revision ID: 63eba25e4054
Revises: 0e2f58f0d553
Create Date: 2020-07-27 13:54:21.235037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63eba25e4054'
down_revision = '0e2f58f0d553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_code', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'Users', ['user_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'user_code')
    # ### end Alembic commands ###
